version: "3.3"

networks:
  backend:
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
  postgres_data:
services:
  order-manager:
    container_name: order-manager
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=orderpass
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_ADDRESS_FROM=noreply@ordermanager.com
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:16
    container_name: postgres-database
    depends_on:
      - mailhog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=orderpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    depends_on:
      - rabbitmq
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3.9.29-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - backend
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/datasource:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - backend