spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/om?currentSchema=order-manager}
    username: ${DATABASE_USER:usr}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false # Set to true when authentication is necessary
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: 'health,metrics,prometheus'
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
app:
  email-address-from:
    email: ${EMAIL_ADDRESS_FROM}
server:
  port: 8080
