spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/om?currentSchema=order-manager}
    username: ${DATABASE_USER:usr}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080
