spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/om?currentSchema=order-manager}
    username: ${DATABASE_USER:usr}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:create-drop}
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080
