{
 "title": "RabbitMQ Metrics",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(rabbitmq_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "{{instance}}:channels" }
   ]
  },
  {
   "title": "Consumed total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_consumed_total", "legendFormat": "{{instance}}:channels" }
   ]
  },
  {
   "title": "Publish total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_published_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Exchanges",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_exchangesTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:exchanges"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queuesTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:queues"
    }
   ]
  },
  {
   "title": "Messages/host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{instance=~\"$instance.*\"}",
     "legendFormat": "{{queue}}:{{durable}}"
    }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  }
 ]
}