global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "order-manager-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "order-manager:8080" ] #Host o container host.docker.internal
        labels:
          application: "order-manager-api"